import {
  Anchor,
  Backpack,
  BookOpen,
  Crosshair,
  FlaskConical,
  Hammer,
  Leaf,
  Music,
  Package,
  PawPrint,
  ScrollText,
  Shield,
  Sparkles,
  Star,
  Sword,
  Truck,
  Wand2,
  Wrench,
  type LucideIcon,
} from "lucide-react";

export const EQUIPMENTS_CATEGORIES_ICONS: Record<string, LucideIcon> = {
  "adventuring-gear": Package,
  ammunition: Crosshair,
  "arcane-foci": Sparkles,
  armor: Shield,
  "artisans-tools": Hammer,
  "druidic-foci": Leaf,
  "equipment-packs": Backpack,
  "gaming-sets": Star,
  "heavy-armor": Shield,
  "holy-symbols": Star,
  kits: Package,
  "land-vehicles": Truck,
  "light-armor": Shield,
  "martial-melee-weapons": Sword,
  "martial-ranged-weapons": Crosshair,
  "martial-weapons": Sword,
  "medium-armor": Shield,
  "melee-weapons": Sword,
  "mounts-and-other-animals": PawPrint,
  "mounts-and-vehicles": Truck,
  "musical-instruments": Music,
  "other-tools": Wrench,
  potion: FlaskConical,
  "ranged-weapons": Crosshair,
  ring: Sparkles,
  rod: Wand2,
  scroll: ScrollText,
  shields: Shield,
  "simple-melee-weapons": Sword,
  "simple-ranged-weapons": Crosshair,
  "simple-weapons": Sword,
  staff: Wand2,
  "standard-gear": Package,
  "tack-harness-and-drawn-vehicles": Truck,
  tools: Wrench,
  wand: Wand2,
  "waterborne-vehicles": Anchor,
  weapon: Sword,
  "wondrous-items": Sparkles,
};

export const EQUIPMENTS_CATEGORIES_FALLBACK_ICON: LucideIcon = BookOpen;
