import {
  Activity,
  Award,
  Backpack,
  BookMarked,
  BookOpen,
  Brain,
  Bug,
  Dumbbell,
  Flame,
  GraduationCap,
  Languages,
  Layers,
  Scale,
  ScrollText,
  Shield,
  ShieldHalf,
  Sparkles,
  Star,
  Sword,
  Tag,
  UserCircle,
  Users,
  Wand2,
  type LucideIcon,
} from "lucide-react";

export const CATEGORY_ICONS: Record<string, LucideIcon> = {
  "ability-scores": Dumbbell,
  alignments: Scale,
  backgrounds: BookOpen,
  classes: Shield,
  conditions: Activity,
  "damage-types": Flame,
  equipment: Backpack,
  "equipment-categories": Layers,
  feats: Star,
  features: Sparkles,
  languages: Languages,
  "magic-items": Wand2,
  "magic-schools": GraduationCap,
  monsters: Bug,
  proficiencies: Award,
  races: Users,
  "rule-sections": BookMarked,
  rules: ScrollText,
  skills: Brain,
  spells: Flame,
  subclasses: ShieldHalf,
  subraces: UserCircle,
  traits: Tag,
  "weapon-properties": Sword,
};

export const CATEGORY_FALLBACK_ICON: LucideIcon = BookOpen;
