import {
  Axe,
  BookOpen,
  Brain,
  Coins,
  Compass,
  Dice5,
  HeartPulse,
  Hourglass,
  Layers,
  Map,
  Moon,
  Shield,
  ShieldCheck,
  Skull,
  Sparkles,
  Swords,
  Timer,
  Wand2,
  Wind,
  type LucideIcon,
} from "lucide-react";

export const RULE_SECTIONS_ICONS: Record<string, LucideIcon> = {
  "ability-checks": Dice5,
  "ability-scores-and-modifiers": Brain,
  "actions-in-combat": Swords,
  "activating-an-item": Wand2,
  "advantage-and-disadvantage": Dice5,
  attunement: Sparkles,
  "between-adventures": Map,
  "casting-a-spell": Wand2,
  cover: Shield,
  "damage-and-healing": HeartPulse,
  diseases: Skull,
  "fantasy-historical-pantheons": Sparkles,
  madness: Brain,
  "making-an-attack": Axe,
  "mounted-combat": Compass,
  movement: Wind,
  "movement-and-position": Compass,
  objects: Layers,
  poisons: Skull,
  "proficiency-bonus": ShieldCheck,
  resting: Moon,
  "saving-throws": ShieldCheck,
  "sentient-magic-items": Sparkles,
  "standard-exchange-rates": Coins,
  "the-environment": Map,
  "the-order-of-combat": Timer,
  "the-planes-of-existence": Sparkles,
  time: Hourglass,
  traps: Shield,
  "underwater-combat": Wind,
  "using-each-ability": Brain,
  "wearing-and-wielding-items": Shield,
  "what-is-a-spell": BookOpen,
};

export const RULE_SECTIONS_FALLBACK_ICON: LucideIcon = BookOpen;
