import {
  Anchor,
  Axe,
  Bell,
  BookOpen,
  Box,
  Crosshair,
  Droplets,
  FileText,
  Fish,
  Flame,
  FlaskConical,
  Gamepad2,
  Ham,
  Hammer,
  Heart,
  Hourglass,
  Leaf,
  Link2,
  Lock,
  Map,
  Music,
  Package,
  Pickaxe,
  Radiation,
  ScrollText,
  Search,
  Shield,
  Shirt,
  Skull,
  Sparkles,
  Sword,
  Tent,
  Wand2,
  Wrench,
  type LucideIcon,
} from "lucide-react";

export const EQUIPMENTS_ICONS: Record<string, LucideIcon> = {
  // Ferramentas de cálculo / escrita
  abacus: FileText,
  "ink-1-ounce-bottle": FileText,
  "ink-pen": FileText,
  "paper-one-sheet": FileText,
  "parchment-one-sheet": ScrollText,
  book: BookOpen,
  spellbook: BookOpen,
  "calligraphers-supplies": FileText,
  "cartographers-tools": Map,
  "navigators-tools": Map,

  // Substâncias / alquimia
  "acid-vial": Radiation,
  "alchemists-fire-flask": Flame,
  "alchemists-supplies": FlaskConical,
  "antitoxin-vial": FlaskConical,
  "holy-water-flask": FlaskConical,
  "oil-flask": Droplets,
  "perfume-vial": Droplets,
  "poison-basic-vial": Skull,
  "poisoners-kit": Skull,
  vial: FlaskConical,
  "bottle-glass": FlaskConical,
  "flask-or-tankard": FlaskConical,
  "jug-or-pitcher": Droplets,

  // Armas - espadas / lâminas
  dagger: Sword,
  longsword: Sword,
  shortsword: Sword,
  greatsword: Sword,
  scimitar: Sword,
  rapier: Sword,
  whip: Sword,
  "war-pick": Sword,
  sickle: Sword,

  // Armas - machados / polearms
  battleaxe: Axe,
  greataxe: Axe,
  handaxe: Axe,
  halberd: Axe,
  glaive: Axe,

  // Armas - martelos / maças
  club: Hammer,
  greatclub: Hammer,
  mace: Hammer,
  morningstar: Hammer,
  maul: Hammer,
  flail: Hammer,
  warhammer: Hammer,
  "light-hammer": Hammer,
  hammer: Hammer,
  "hammer-sledge": Hammer,

  // Armas - hastes / lanças
  spear: Sword,
  pike: Sword,
  lance: Sword,
  trident: Sword,
  quarterstaff: Sword,
  staff: Wand2,
  "wooden-staff": Wand2,
  javelin: Sword,

  // Armas - arcos / projéteis
  longbow: Crosshair,
  shortbow: Crosshair,
  "crossbow-hand": Crosshair,
  "crossbow-heavy": Crosshair,
  "crossbow-light": Crosshair,
  sling: Crosshair,
  blowgun: Crosshair,
  net: Anchor,

  // Munição
  arrow: Crosshair,
  "crossbow-bolt": Crosshair,
  "sling-bullet": Crosshair,
  "blowgun-needle": Crosshair,
  dart: Crosshair,

  // Armaduras
  "chain-mail": Shield,
  "chain-shirt": Shield,
  "half-plate-armor": Shield,
  "hide-armor": Shield,
  "leather-armor": Shield,
  "padded-armor": Shield,
  "plate-armor": Shield,
  "ring-mail": Shield,
  "scale-mail": Shield,
  "splint-armor": Shield,
  "studded-leather-armor": Shield,
  breastplate: Shield,
  robes: Shirt,
  shield: Shield,

  // Bardamentos (armaduras de montaria)
  "barding-breastplate": Shield,
  "barding-chain-mail": Shield,
  "barding-chain-shirt": Shield,
  "barding-half-plate": Shield,
  "barding-hide": Shield,
  "barding-leather": Shield,
  "barding-padded": Shield,
  "barding-plate": Shield,
  "barding-ring-mail": Shield,
  "barding-scale-mail": Shield,
  "barding-splint": Shield,
  "barding-studded-leather": Shield,

  // Focos arcanos / religiosos
  crystal: Sparkles,
  orb: Sparkles,
  rod: Wand2,
  wand: Wand2,
  "yew-wand": Wand2,
  amulet: Sparkles,
  emblem: Sparkles,
  reliquary: Sparkles,
  totem: Sparkles,
  "sprig-of-mistletoe": Leaf,
  vestments: Shirt,
  censer: Sparkles,
  "block-of-incense": Sparkles,
  "alms-box": Box,

  // Mochilas / kits de aventura
  backpack: Package,
  "burglars-pack": Package,
  "diplomats-pack": Package,
  "dungeoneers-pack": Package,
  "entertainers-pack": Package,
  "explorers-pack": Package,
  "priests-pack": Package,
  "scholars-pack": Package,
  pouch: Package,
  sack: Package,
  quiver: Package,
  "component-pouch": Package,

  // Contêineres / armazenamento
  barrel: Box,
  basket: Box,
  bucket: Box,
  chest: Box,
  "case-crossbow-bolt": Box,
  "case-map-or-scroll": ScrollText,
  "pot-iron": Box,

  // Instrumentos musicais
  bagpipes: Music,
  drum: Music,
  dulcimer: Music,
  flute: Music,
  horn: Music,
  lute: Music,
  lyre: Music,
  "pan-flute": Music,
  shawm: Music,
  viol: Music,

  // Ferramentas / kits
  "brewers-supplies": FlaskConical,
  "carpenters-tools": Wrench,
  "cobblers-tools": Wrench,
  "cooks-utensils": Wrench,
  "forgery-kit": FileText,
  "glassblowers-tools": Wrench,
  "herbalism-kit": Leaf,
  "jewelers-tools": Sparkles,
  "leatherworkers-tools": Wrench,
  "masons-tools": Wrench,
  "painters-supplies": Wrench,
  "potters-tools": Wrench,
  "smiths-tools": Hammer,
  "thieves-tools": Lock,
  "tinkers-tools": Wrench,
  "weavers-tools": Wrench,
  "woodcarvers-tools": Wrench,
  "disguise-kit": Shirt,

  // Iluminação
  candle: Flame,
  lamp: Flame,
  "lantern-bullseye": Flame,
  "lantern-hooded": Flame,
  torch: Flame,
  tinderbox: Flame,

  // Escalada / exploração
  "climbers-kit": Anchor,
  "grappling-hook": Anchor,
  "rope-hempen-50-feet": Link2,
  "rope-silk-50-feet": Link2,
  "chain-10-feet": Link2,
  "string-10-feet": Link2,
  "block-and-tackle": Link2,
  "hunting-trap": Lock,
  manacles: Link2,
  caltrops: Sword,
  "ball-bearings-bag-of-1000": Wrench,
  crowbar: Wrench,
  "pick-miners": Pickaxe,
  shovel: Wrench,
  piton: Anchor,
  "ladder-10-foot": Wrench,
  "pole-10-foot": Sword,
  "ram-portable": Hammer,

  // Saúde / sobrevivência
  "healers-kit": Heart,
  "mess-kit": Ham,
  "rations-1-day": Ham,
  "animal-feed-1-day": Ham,
  waterskin: Droplets,
  soap: Droplets,
  blanket: Tent,
  bedroll: Tent,
  "tent-two-person": Tent,

  // Navegação / veículos
  galley: Anchor,
  keelboat: Anchor,
  longship: Anchor,
  rowboat: Anchor,
  "sailing-ship": Anchor,
  warship: Anchor,
  carriage: Package,
  cart: Package,
  chariot: Package,
  sled: Package,
  wagon: Package,

  // Montarias
  camel: Package,
  donkey: Package,
  elephant: Package,
  "horse-draft": Package,
  "horse-riding": Package,
  mastiff: Package,
  mule: Package,
  pony: Package,
  warhorse: Package,
  "stabling-1-day": Package,

  // Selas / acessórios de montaria
  "bit-and-bridle": Link2,
  "saddle-exotic": Package,
  "saddle-military": Package,
  "saddle-pack": Package,
  "saddle-riding": Package,
  saddlebags: Package,

  // Instrumentos de precisão / observação
  hourglass: Hourglass,
  "magnifying-glass": Search,
  spyglass: Search,
  "mirror-steel": Search,
  "scale-merchants": FileText,

  // Pesca / natureza
  "fishing-tackle": Fish,

  // Jogos / entretenimento
  "dice-set": Gamepad2,
  "playing-card-set": Gamepad2,

  // Itens gerais / religiosos
  bell: Bell,
  lock: Lock,
  "signal-whistle": Bell,
  "signet-ring": Sparkles,
  "sealing-wax": FileText,
  "little-bag-of-sand": Package,
  "small-knife": Sword,
  "spike-iron": Sword,
  // "hammer-sledge": Hammer,
  "chalk-1-piece": FileText,
};

export const EQUIPMENTS_FALLBACK_ICON: LucideIcon = BookOpen;
