import {
  BookOpen,
  Flame,
  Music,
  Swords,
  Sun,
  Star,
  Leaf,
  Target,
  Eye,
  Sparkles,
  Ghost,
  Wand2,
  Shield,
  Wind,
  Zap,
  Heart,
  Compass,
  RefreshCw,
  type LucideIcon,
} from "lucide-react";

export const FEATURES_ICONS: Record<string, LucideIcon> = {
  // Barbarian
  rage: Flame,
  "unarmored-defense-barbarian": Shield,
  "danger-sense": Eye,
  "reckless-attack": Swords,
  "primal-path": Flame,
  "extra-attack-2": Swords,
  "fast-movement": Wind,
  "feral-instinct": Eye,
  "brutal-critical-1-die": Swords,
  "brutal-critical-2-dice": Swords,
  "brutal-critical-3-dice": Swords,
  "relentless-rage": Flame,
  "persistent-rage": Flame,
  "indomitable-might": Shield,
  "primal-champion": Star,
  "barbarian-ability-score-improvement-1": Shield,
  "barbarian-ability-score-improvement-2": Shield,
  "barbarian-ability-score-improvement-3": Shield,
  "barbarian-ability-score-improvement-4": Shield,
  "barbarian-ability-score-improvement-5": Shield,
  "barbarian-extra-attack": Swords,
  "barbarian-unarmored-defense": Shield,

  // Bard
  "spellcasting-bard": Sparkles,
  "bardic-inspiration-d6": Music,
  "bardic-inspiration-d8": Music,
  "bardic-inspiration-d10": Music,
  "bardic-inspiration-d12": Music,
  "jack-of-all-trades": Star,
  "song-of-rest-d6": Music,
  "song-of-rest-d8": Music,
  "song-of-rest-d10": Music,
  "song-of-rest-d12": Music,
  "bard-college": Music,
  "expertise-bard": Star,
  "font-of-inspiration": Music,
  countercharm: Music,
  "magical-secrets": Sparkles,
  "superior-inspiration": Music,
  "additional-magical-secrets": Sparkles,
  "bard-ability-score-improvement-1": Shield,
  "bard-ability-score-improvement-2": Shield,
  "bard-ability-score-improvement-3": Shield,
  "bard-ability-score-improvement-4": Shield,
  "bard-ability-score-improvement-5": Shield,

  // Cleric
  "spellcasting-cleric": Sun,
  "divine-domain": Sun,
  "channel-divinity-cleric": Sun,
  "channel-divinity-turn-undead": Sun,
  "channel-divinity-2-rest": Sun,
  "channel-divinity-3-rest": Sun,
  "destroy-undead-cr-1-2": Sun,
  "destroy-undead-cr-1": Sun,
  "destroy-undead-cr-2": Sun,
  "destroy-undead-cr-3": Sun,
  "destroy-undead-cr-4": Sun,
  "divine-intervention": Sun,
  "divine-intervention-improvement": Sun,

  // Druid
  druidic: Leaf,
  "spellcasting-druid": Leaf,
  "wild-shape": RefreshCw,
  "wild-shape-improvement": RefreshCw,
  "druid-circle": Leaf,
  "timeless-body-druid": Leaf,
  "beast-spells": Leaf,
  archdruid: Leaf,

  // Fighter
  "fighting-style-fighter": Swords,
  "second-wind": Wind,
  "action-surge-1-use": Zap,
  "action-surge-2-uses": Zap,
  "martial-archetype": Swords,
  "extra-attack": Swords,
  "extra-attack-3": Swords,
  "extra-attack-4": Swords,
  "indomitable-1-use": Shield,
  "indomitable-2-uses": Shield,
  "indomitable-3-uses": Shield,
  "additional-fighting-style": Swords,

  // Monk
  "unarmored-defense-monk": Shield,
  "martial-arts": Flame,
  ki: Sparkles,
  "unarmored-movement": Wind,
  "unarmored-movement-improvement": Wind,
  "monastic-tradition": Flame,
  "deflect-missiles": Shield,
  "slow-fall": Wind,
  "extra-attack-monk": Swords,
  "stunning-strike": Zap,
  "ki-empowered-strikes": Sparkles,
  evasion: Wind,
  "stillness-of-mind": Sparkles,
  "purity-of-body": Heart,
  "tongue-of-sun-and-moon": Sun,
  "diamond-soul": Star,
  "timeless-body-monk": Star,
  "empty-body": Ghost,
  "perfect-self": Star,

  // Paladin
  "divine-sense": Sun,
  "lay-on-hands": Heart,
  "fighting-style-paladin": Swords,
  "spellcasting-paladin": Star,
  "divine-smite": Star,
  "divine-health": Heart,
  "sacred-oath": Star,
  "extra-attack-paladin": Swords,
  "aura-of-protection": Shield,
  "aura-of-courage": Shield,
  "improved-divine-smite": Star,
  "cleansing-touch": Heart,
  "aura-improvements": Shield,
  "aura-of-devotion": Shield,
  // Ranger
  "favored-enemy-1-type": Target,
  "favored-enemy-2-types": Target,
  "favored-enemy-3-types": Target,
  "natural-explorer-1-terrain": Compass,
  "natural-explorer-2-terrains": Compass,
  "natural-explorer-3-terrains": Compass,
  "fighting-style-ranger": Swords,
  "spellcasting-ranger": Leaf,
  "ranger-archetype": Target,
  "primeval-awareness": Eye,
  "extra-attack-ranger": Swords,
  "lands-stride": Compass,
  "hide-in-plain-sight": Eye,
  vanish: Eye,
  "feral-senses": Eye,
  "foe-slayer": Target,

  // Rogue
  "expertise-rogue": Eye,
  "sneak-attack": Eye,
  "thieves-cant": Eye,
  "cunning-action": Zap,
  "roguish-archetype": Eye,
  "uncanny-dodge": Shield,
  "expertise-rogue-2": Eye,
  "evasion-rogue": Wind,
  "reliable-talent": Star,
  blindsense: Eye,
  "slippery-mind": Shield,
  elusive: Ghost,
  "stroke-of-luck": Star,

  // Sorcerer
  "spellcasting-sorcerer": Sparkles,
  "sorcerous-origin": Sparkles,
  "font-of-magic": Sparkles,
  metamagic: Sparkles,
  "sorcerous-restoration": Sparkles,

  // Warlock
  "otherworldly-patron": Ghost,
  "pact-magic": Ghost,
  "eldritch-invocations": Ghost,
  "pact-boon": Ghost,
  "mystic-arcanum-6th-level": Wand2,
  "mystic-arcanum-7th-level": Wand2,
  "mystic-arcanum-8th-level": Wand2,
  "mystic-arcanum-9th-level": Wand2,
  "eldritch-master": Ghost,

  // Wizard
  "spellcasting-wizard": Wand2,
  "arcane-recovery": Wand2,
  "arcane-tradition": Wand2,
  "spell-mastery": BookOpen,
  "signature-spell": Wand2,
  "arcane-tradition-improvement-1": Wand2,
  "arcane-tradition-improvement-2": Wand2,
  "arcane-tradition-improvement-3": Wand2,
};

export const FEATURES_FALLBACK_ICON: LucideIcon = BookOpen;
